apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-d
resources:
  - manager.yaml
  - rbac.yaml
configMapGenerator:
  - name: resiliency-manager-config
    files:
      - config.yaml
